version: "3.2"
services:
  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: trainingapp
      MYSQL_USER: foo
      MYSQL_PASSWORD: bar